### ISSUE TITLE
Error when launch 

### ISSUE THREAD

**Issue by SyahirMuzni** [autocore-ai/calibration_tools#2]
I have successfully built the package. But I encountered an error when I launched the package. It appears, to be the errors from *pcl_utils.h*. 

![error](https://user-images.githubusercontent.com/94072577/198978867-9fca0320-14ae-4b50-970b-30b6338513e7.png)

**Comment by JianKangEgon** [comment]
@SyahirMuzni hi, thanks for asking. Well, this error was caused by the data collection and easy to solve. The lidar point cloud is supposed to be organized, i.e. 3D lidar point cloud with height * width. For example, the sample data set contains the 64*1028 point cloud. You could search the related tutorials to modify the config file of your lidar sensor driver
